// Car data for Tunisia
carsData = [
  {
    id: 1,
    name: "Peugeot 208",
    year: 2022,
    price: 120,
    image: "images/cars/placeholder.svg",
    brand: "peugeot",
    type: "compact",
    category: "popular",
    mileage: "4000 km",
    transmission: "Manuelle",
    seats: 5,
    fuel: "Essence",
  },
  {
    id: 2,
    name: "Renault Clio",
    year: 2021,
    price: 110,
    image: "images/cars/placeholder.svg",
    brand: "renault",
    type: "compact",
    category: "popular",
    mileage: "5000 km",
    transmission: "Manuelle",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 3,
    name: "Volkswagen Golf",
    year: 2022,
    price: 150,
    image: "images/cars/placeholder.svg",
    brand: "volkswagen",
    type: "compact",
    category: "popular",
    mileage: "3500 km",
    transmission: "Automatique",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 4,
    name: "Dacia Duster",
    year: 2021,
    price: 130,
    image: "images/cars/placeholder.svg",
    brand: "dacia",
    type: "suv",
    category: "family",
    mileage: "6000 km",
    transmission: "Manuelle",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 5,
    name: "Citroen C3",
    year: 2022,
    price: 115,
    image: "images/cars/placeholder.svg",
    brand: "citroen",
    type: "compact",
    category: "popular",
    mileage: "4200 km",
    transmission: "Manuelle",
    seats: 5,
    fuel: "Essence",
  },
  {
    id: 6,
    name: "Fiat 500",
    year: 2021,
    price: 100,
    image: "images/cars/placeholder.svg",
    brand: "fiat",
    type: "compact",
    category: "popular",
    mileage: "3800 km",
    transmission: "Manuelle",
    seats: 4,
    fuel: "Essence",
  },
  {
    id: 7,
    name: "Audi A4",
    year: 2022,
    price: 250,
    image: "images/cars/placeholder.svg",
    brand: "audi",
    type: "sedan",
    category: "luxury",
    mileage: "2500 km",
    transmission: "Automatique",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 8,
    name: "Mercedes-Benz Classe C",
    year: 2022,
    price: 280,
    image: "images/cars/placeholder.svg",
    brand: "mercedes-benz",
    type: "sedan",
    category: "luxury",
    mileage: "2000 km",
    transmission: "Automatique",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 9,
    name: "BMW Série 3",
    year: 2022,
    price: 270,
    image: "images/cars/placeholder.svg",
    brand: "bmw",
    type: "sedan",
    category: "luxury",
    mileage: "2200 km",
    transmission: "Automatique",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 10,
    name: "Jeep Wrangler",
    year: 2021,
    price: 220,
    image: "images/cars/placeholder.svg",
    brand: "jeep",
    type: "suv",
    category: "off-road",
    mileage: "5500 km",
    transmission: "Manuelle",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 11,
    name: "Renault Megane",
    year: 2022,
    price: 140,
    image: "images/cars/placeholder.svg",
    brand: "renault",
    type: "sedan",
    category: "family",
    mileage: "4500 km",
    transmission: "Manuelle",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 12,
    name: "Peugeot 3008",
    year: 2022,
    price: 180,
    image: "images/cars/placeholder.svg",
    brand: "peugeot",
    type: "suv",
    category: "family",
    mileage: "3800 km",
    transmission: "Automatique",
    seats: 5,
    fuel: "Diesel",
  },
]

// Testimonials data
const testimonialsData = [
  {
    id: 1,
    name: "Ahmed Ben Ali",
    location: "Tunis",
    image: "images/testimonials/placeholder.svg",
    text: "J'ai été vraiment impressionné par le niveau de service que j'ai reçu de cette société de location de voitures. Le processus était fluide et facile, et la voiture que j'ai louée était en excellent état. Le personnel était amical et serviable, et je me suis senti bien pris en charge tout au long de ma période de location. Je recommanderais certainement cette entreprise à quiconque recherche une expérience de location de voiture premium.",
  },
  {
    id: 2,
    name: "Sarra Mansouri",
    location: "Sousse",
    image: "images/testimonials/placeholder.svg",
    text: "Service excellent ! La voiture a été livrée à temps et en parfait état. Le processus de location était simple, et le personnel était très professionnel. J'utiliserai certainement leurs services à nouveau pour mon prochain voyage en Tunisie.",
  },
  {
    id: 3,
    name: "Mohamed Karim",
    location: "Sfax",
    image: "images/testimonials/placeholder.svg",
    text: "J'ai loué une voiture pour un voyage en famille d'une semaine à travers la Tunisie, et je ne pourrais pas être plus satisfait du service. La voiture était confortable, économe en carburant et parfaite pour nos besoins. Les prix étaient transparents sans frais cachés. Hautement recommandé !",
  },
]
