export const carsData = [
  {
    id: 1,
    name: "Peugeot 208",
    year: 2022,
    price: 120,
    image: "https://images.pexels.com/photos/18471354/pexels-photo-18471354/free-photo-of-a-car-in-a-parking-lot.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    brand: "peugeot",
    type: "compact",
    category: "popular",
    mileage: "4000 km",
    transmission: "Manuelle",
    seats: 5,
    fuel: "Essence",
  },
  {
    id: 2,
    name: "Renault Clio",
    year: 2021,
    price: 110,
    image: "https://images.pexels.com/photos/16634658/pexels-photo-16634658/free-photo-of-a-black-modern-renault-clio-sport.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    brand: "renault",
    type: "compact",
    category: "popular",
    mileage: "5000 km",
    transmission: "Manuelle",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 3,
    name: "Volkswagen Golf",
    year: 2022,
    price: 150,
    image: "https://images.pexels.com/photos/10843557/pexels-photo-10843557.jpeg?auto=compress&cs=tinysrgb&w=600",
    brand: "volkswagen",
    type: "compact",
    category: "popular",
    mileage: "3500 km",
    transmission: "Automatique",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 4,
    name: "Dacia Duster",
    year: 2021,
    price: 130,
    image: "https://images.pexels.com/photos/19922984/pexels-photo-19922984/free-photo-of-red-dacia-duster-left-on-the-roadside.jpeg?auto=compress&cs=tinysrgb&w=600",
    brand: "dacia",
    type: "suv",
    category: "family",
    mileage: "6000 km",
    transmission: "Manuelle",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 5,
    name: "Citroen C3",
    year: 2022,
    price: 115,
    image: "https://tunisie-enchere.com/media/offre/269/1652454204_424_269.jpg",
    brand: "citroen",
    type: "compact",
    category: "popular",
    mileage: "4200 km",
    transmission: "Manuelle",
    seats: 5,
    fuel: "Essence",
  },
  {
    id: 6,
    name: "Fiat Punto",
    year: 1998,
    price: 100,
    image: "https://www.mediastorehouse.com/p/767/fiat-punto-55-exterior-car-doors-open-green-21508563.jpg.webp",
    brand: "fiat",
    type: "compact",
    category: "popular",
    mileage: "13000 km",
    transmission: "Manuelle",
    seats: 5,
    fuel: "Essence",
  },
  {
    id: 7,
    name: "Audi A4",
    year: 2022,
    price: 250,
    image: "https://images.pexels.com/photos/30164532/pexels-photo-30164532/free-photo-of-front-view-of-red-audi-a4-in-urban-setting.jpeg?auto=compress&cs=tinysrgb&w=600",
    brand: "audi",
    type: "sedan",
    category: "luxury",
    mileage: "2500 km",
    transmission: "Automatique",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 8,
    name: "Mercedes-Benz Classe C",
    year: 2022,
    price: 280,
    image: "https://images.pexels.com/photos/27019870/pexels-photo-27019870/free-photo-of-blue-car-parked-near-bushes.jpeg?auto=compress&cs=tinysrgb&w=600",
    brand: "mercedes-benz",
    type: "sedan",
    category: "luxury",
    mileage: "2000 km",
    transmission: "Automatique",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 9,
    name: "BMW Série 3",
    year: 2022,
    price: 270,
    image: "https://images.pexels.com/photos/12086412/pexels-photo-12086412.jpeg?auto=compress&cs=tinysrgb&w=600",
    brand: "bmw",
    type: "sedan",
    category: "luxury",
    mileage: "2200 km",
    transmission: "Automatique",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 10,
    name: "Jeep Wrangler",
    year: 2021,
    price: 220,
    image: "https://images.pexels.com/photos/13118533/pexels-photo-13118533.jpeg?auto=compress&cs=tinysrgb&w=600",
    brand: "jeep",
    type: "suv",
    category: "off-road",
    mileage: "5500 km",
    transmission: "Manuelle",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 10,
    name: "Renault Megane",
    year: 2022,
    price: 140,
    image: "https://images.pexels.com/photos/6747187/pexels-photo-6747187.jpeg?auto=compress&cs=tinysrgb&w=600",
    brand: "renault",
    type: "sedan",
    category: "family",
    mileage: "4500 km",
    transmission: "Manuelle",
    seats: 5,
    fuel: "Diesel",
  },
  {
    id: 11,
    name: "Peugeot 3008",
    year: 2022,
    price: 180,
    image: "https://images.pexels.com/photos/14121166/pexels-photo-14121166.jpeg?auto=compress&cs=tinysrgb&w=600",
    brand: "peugeot",
    type: "suv",
    category: "family",
    mileage: "3800 km",
    transmission: "Automatique",
    seats: 5,
    fuel: "Diesel",
  },
]

export const brandsData = [
  {
    id: 1,
    brand: "Peugeot",
    image: "images/brands/peugeot.svg",
  },
  {
    id: 2,
    brand: "Renault",
    image: "images/brands/renault.svg",
  },
  {
    id: 3,
    brand: "Citroen",
    image: "images/brands/citroen.svg",
  }, 
  {
    id: 4,
    brand: "Volkswagen",
    image: "images/brands/volkswagen.svg",
  },
  {
    id: 5,
    brand: "Fiat",
    image: "images/brands/fiat.svg",
  },
  {
    id: 6,
    brand: "Dacia",
    location: "Sfax",
    image: "images/brands/dacia.svg",
  },
]

export const typesData = [
  {
    id: 1,
    type: "SUV",
    icon: "images/assets/types/suv.png",
  },
  {
    id: 2,
    type: "Crossover",
    icon: "images/assets/types/crossover.png",
  },
  {
    id: 3,
    type: "Wagon",
    icon: "images/assets/types/wagon.png",
  },
  {
    id: 4,
    type: "Family",
    icon: "images/assets/types/family.png",
  },
  {
    id: 5,
    type: "Sport Coupe",
    icon: "images/assets/types/sport.png",
  },
  {
    id: 6,
    type: "Compact",
    icon: "images/assets/types/compact.png",
  },
  {
    id: 7,
    type: "Pickup",
    icon: "images/assets/types/pickup.png",
  },
  {
    id: 8,
    type: "Sedan",
    icon: "images/assets/types/sedan.png",
  },
  {
    id: 9,
    type: "Limousine",
    icon: "images/assets/types/limousine.png",
  },
  {
    id: 10,
    type: "Convertible",
    icon: "images/assets/types/convertible.png",
  },
  {
    id: 11,
    type: "Minivan",
    icon: "images/assets/types/van.png",
  }, 
  {
    id: 12,
    type: "Electrique",
    icon: "images/assets/types/electric-car.png"
  },

]
